import { dateBR, money } from './utils.js'
import { getCompany, getContact, proposalTotals, serviceNames } from './domain.js'

const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))
const nl=value=>esc(value||'').replace(/\n/g,'<br>')

export function printProposal(state,opp,proposal){
  const contact=getContact(state,opp),company=getCompany(state,opp),totals=proposalTotals(proposal)
  const win=window.open('','_blank','noopener,noreferrer')
  if(!win)return false
  const rows=(proposal.items||[]).map(item=>`<tr><td><strong>${esc(item.name)}</strong></td><td class="num">${money(item.oneOff)}</td><td class="num">${money(item.mrr)}/mês</td></tr>`).join('')
  const sections=[
    proposal.scope&&`<section><h2>Escopo do serviço</h2><p>${nl(proposal.scope)}</p></section>`,
    proposal.notIncluded&&`<section><h2>Não incluído</h2><p>${nl(proposal.notIncluded)}</p></section>`,
    proposal.deadline&&`<section><h2>Prazo estimado</h2><p>${nl(proposal.deadline)}</p></section>`,
    proposal.payment&&`<section><h2>Condição de pagamento</h2><p>${nl(proposal.payment)}</p></section>`,
    proposal.clientNotes&&`<section><h2>Observações ao cliente</h2><p>${nl(proposal.clientNotes)}</p></section>`,
  ].filter(Boolean).join('')

  win.document.write(`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Proposta ${esc(proposal.code||'Comercial')} · V${proposal.version}</title><style>
    @page{size:A4;margin:15mm}*{box-sizing:border-box}body{margin:0;color:#182230;font-family:Arial,Helvetica,sans-serif;font-size:11.5pt;line-height:1.55;background:#fff}.page{max-width:180mm;margin:auto}.top{display:flex;justify-content:space-between;gap:24px;padding-bottom:18px;border-bottom:3px solid #2456E8}.brand{display:flex;gap:12px;align-items:center}.mark{width:46px;height:46px;border-radius:10px;background:#2456E8;color:white;display:grid;place-items:center;font-weight:700;font-size:16px}.brand strong{display:block;font-size:15px}.brand span,.meta span,.muted{color:#667085;font-size:10px}.meta{text-align:right}.meta b{display:block;font-size:13px}.hero{padding:26px 0 18px}.eyebrow{font-size:9px;font-weight:700;color:#2456E8;letter-spacing:.08em;text-transform:uppercase}.hero h1{font-size:26px;line-height:1.15;margin:5px 0 8px}.client{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:12px 0 22px}.client div{padding:12px 14px;background:#F6F8FC;border:1px solid #E4E9F1;border-radius:10px}.client span{display:block;color:#667085;font-size:9px;font-weight:700;text-transform:uppercase;letter-spacing:.05em}.client b{display:block;margin-top:4px}.summary{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:16px 0 22px}.summary div{padding:14px;border-radius:10px;border:1px solid #D8E2FF;background:#F7F9FF}.summary span{display:block;color:#667085;font-size:9px;font-weight:700;text-transform:uppercase}.summary b{display:block;margin-top:4px;font-size:19px}.summary small{display:block;color:#667085;margin-top:3px}table{width:100%;border-collapse:collapse;margin:10px 0 22px}th,td{padding:10px 8px;border-bottom:1px solid #E4E9F1;text-align:left}th{font-size:9px;color:#667085;text-transform:uppercase}.num{text-align:right;white-space:nowrap}section{margin:18px 0}section h2{font-size:12px;margin:0 0 6px}section p{margin:0;color:#344054}.validity{margin-top:24px;padding:12px 14px;border-left:4px solid #2456E8;background:#F6F8FC}.footer{margin-top:34px;padding-top:14px;border-top:1px solid #E4E9F1;display:flex;justify-content:space-between;gap:16px;color:#667085;font-size:9px}.actions{position:fixed;right:18px;bottom:18px;display:flex;gap:8px}.actions button{border:1px solid #CDD5DF;border-radius:9px;background:#fff;padding:10px 14px;font-weight:700}.actions .primary{border-color:#2456E8;background:#2456E8;color:#fff}@media print{.actions{display:none}.page{max-width:none}}
  </style></head><body><main class="page"><header class="top"><div class="brand"><div class="mark">LG</div><div><strong>Contador Luid Gabriel</strong><span>Contabilidade clara para decisões melhores</span></div></div><div class="meta"><span>PROPOSTA COMERCIAL</span><b>${esc(proposal.code||'—')} · V${proposal.version}</b><span>Emitida em ${dateBR(proposal.createdAt)}</span></div></header><div class="hero"><div class="eyebrow">Proposta personalizada</div><h1>${esc(serviceNames(opp))}</h1><p class="muted">Uma proposta construída conforme a necessidade identificada no atendimento comercial.</p></div><div class="client"><div><span>Cliente</span><b>${esc(contact?.name||'—')}</b><small>${esc(contact?.phone||contact?.email||'')}</small></div><div><span>Empresa</span><b>${esc(company?.name||'—')}</b><small>${esc(company?.doc||company?.type||'')}</small></div></div><div class="summary"><div><span>Serviços / implantação</span><b>${money(totals.oneOff)}</b><small>Valor avulso total após desconto</small></div><div><span>Mensalidade</span><b>${money(totals.mrr)}</b><small>MRR dos serviços recorrentes</small></div></div><table><thead><tr><th>Serviço</th><th class="num">Avulso</th><th class="num">Mensalidade</th></tr></thead><tbody>${rows}</tbody></table>${sections}<div class="validity"><strong>Validade da proposta:</strong> ${proposal.validity?dateBR(proposal.validity):'não informada'}${proposal.notes?`<br><span>${nl(proposal.notes)}</span>`:''}</div><footer class="footer"><span>Contador Luid Gabriel</span><span>Proposta ${esc(proposal.code||'comercial')} · versão ${proposal.version}</span></footer></main><div class="actions"><button onclick="window.close()">Fechar</button><button class="primary" onclick="window.print()">Imprimir / Salvar PDF</button></div></body></html>`)
  win.document.close()
  return true
}
