import React from 'react'
import MetricCard from '../components/MetricCard.jsx'
import { useCrm } from '../context/CrmContext.jsx'
import { activeOpportunity, getContact, isActivityOverdue, lastInteractionDate, nextActivity, opportunityValueText, periodLabel, pipelineSummary, reportData, scoreLead, serviceNames } from '../lib/domain.js'
import { dateBR, daysSince, money } from '../lib/utils.js'

export default function Central({openOpportunity,openActivity}){
 const {state,uiPeriod}=useCrm(),summary=pipelineSummary(state),report=reportData(state,uiPeriod)
 const stale=state.opportunities.filter(o=>activeOpportunity(o)&&daysSince(lastInteractionDate(o))>=state.settings.staleDays)
 const priorities=state.opportunities.filter(activeOpportunity).map(o=>{const a=nextActivity(state,o.id);return{o,score:scoreLead(state,o),stale:daysSince(lastInteractionDate(o)),overdue:a&&isActivityOverdue(a)}}).sort((a,b)=>(b.score+(b.overdue?15:0)+(b.stale>=state.settings.staleDays?10:0))-(a.score+(a.overdue?15:0)+(a.stale>=state.settings.staleDays?10:0))).slice(0,6)
 const period=periodLabel(uiPeriod)
 return <>
  <div className="metrics-grid"><MetricCard label="Oportunidades ativas" value={summary.count} hint="Visão atual · adiados ficam fora"/><MetricCard label="Pipeline avulso" value={money(summary.oneOff)} hint="Potencial atual"/><MetricCard label="Pipeline MRR" value={money(summary.mrr)} hint="Mensalidade potencial atual"/><MetricCard label="Leads parados" value={stale.length} hint={`≥ ${state.settings.staleDays} dias sem interação`} tone={stale.length?'attention':''}/></div>
  <div className="central-grid"><section className="panel"><header className="panel-head"><h2>Faça isso agora</h2><span className="pill danger">{priorities.length} prioridades</span></header><div className="panel-body list-stack">{priorities.map((x,i)=>{const c=getContact(state,x.o),a=nextActivity(state,x.o.id);return <article className="priority-card" key={x.o.id}><span className="rank">{i+1}</span><div className="grow"><div className="between"><div><b>{c?.name}</b><p>{serviceNames(x.o)} · {x.o.stage}</p></div><span className="score">Score {x.score}/100</span></div><p className="value-line">{opportunityValueText(x.o)}</p><div className="next-action"><span>Próxima ação</span><b>{a?`${a.type} · ${dateBR(a.date)}${a.time?` às ${a.time}`:''}`:x.stale>=state.settings.staleDays?`Retomar contato — ${x.stale} dias parado`:'Agendar próximo passo'}</b></div><div className="actions"><button className="btn small primary" onClick={()=>openOpportunity(x.o.id)}>Abrir</button><button className="btn small" onClick={()=>openActivity(x.o.id)}>Agendar</button></div></div></article>})}{!priorities.length&&<div className="empty">Nenhuma prioridade pendente.</div>}</div></section>
  <section className="panel"><header className="panel-head"><h2>{uiPeriod==='month'?'Metas do mês':`Resultados · ${period}`}</h2></header><div className="panel-body">{uiPeriod==='month'?<><Goal label="Novos clientes" current={report.won.length} target={state.settings.goals.clients}/><Goal label="Novo MRR" current={report.revenue.mrr} target={state.settings.goals.mrr} moneyMode/><Goal label="Receita avulsa" current={report.revenue.oneOff} target={state.settings.goals.oneOff} moneyMode/></>:<div className="revenue-stack"><div><span>Leads recebidos</span><b>{report.created.length}</b></div><div><span>Vendas fechadas</span><b>{report.won.length}</b></div><div><span>Novo MRR</span><b>{money(report.revenue.mrr)}</b></div></div>}<div className="notice success"><b>{report.conversion.toFixed(1)}% das decisões viraram venda</b><br/>{report.won.length} ganhos em {report.won.length+report.lost.length} decisões fechadas em {period.toLowerCase()}.</div></div></section></div>
  <div className="two-grid"><section className="panel"><header className="panel-head"><h2>Leads esquecidos</h2><span className="pill warning">{stale.length}</span></header><div className="panel-body list-stack">{stale.slice(0,6).map(o=><button className="list-row button-row" key={o.id} onClick={()=>openOpportunity(o.id)}><span className="status-dot warning"/><span><b>{getContact(state,o)?.name}</b><small>{serviceNames(o)} · {daysSince(lastInteractionDate(o))} dias sem interação</small></span></button>)}{!stale.length&&<div className="empty">Nenhum lead esquecido.</div>}</div></section><section className="panel"><header className="panel-head"><h2>Financeiro · {period}</h2></header><div className="panel-body revenue-stack"><div><span>Avulso fechado</span><b>{money(report.revenue.oneOff)}</b></div><div><span>Novo MRR</span><b>{money(report.revenue.mrr)}</b></div><div><span>Adiadas</span><b>{summary.deferredCount} oportunidades</b><small>{money(summary.deferred.oneOff)} · {money(summary.deferred.mrr)}/mês fora do pipeline ativo</small></div></div></section></div>
 </>
}
function Goal({label,current,target,moneyMode}){const pct=Math.min(100,target?current/target*100:0);return <div className="goal"><div className="between"><span>{label}</span><b>{moneyMode?money(current):current} / {moneyMode?money(target):target}</b></div><div className="progress"><span style={{width:`${pct}%`}}/></div></div>}
