import React, { useState } from 'react'
import { useCrm } from '../context/CrmContext.jsx'
import { getCompany, opportunityTotals, scoreLead, serviceNames } from '../lib/domain.js'
import { money } from '../lib/utils.js'
export default function Leads({openOpportunity,newForContact}){
 const {state}=useCrm();const[q,setQ]=useState('');const[mode,setMode]=useState('all')
 const contacts=state.contacts.filter(c=>{const related=state.opportunities.filter(o=>o.contactId===c.id).map(serviceNames).join(' ');return !q||`${c.name} ${c.phone} ${c.email} ${related}`.toLowerCase().includes(q.toLowerCase())})
 return <><div className="filter-row"><button className="filter-chip" aria-pressed={mode==='all'} onClick={()=>setMode('all')}>Contatos</button><button className="filter-chip" aria-pressed={mode==='opps'} onClick={()=>setMode('opps')}>Oportunidades</button></div><div className="toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Nome, WhatsApp, e-mail ou serviço"/></div>{mode==='all'?<section className="panel table-wrap"><table><thead><tr><th>Contato</th><th>Empresa</th><th>Oportunidades</th><th>Ativas</th><th>MRR ganho</th><th></th></tr></thead><tbody>{contacts.map(c=>{const opps=state.opportunities.filter(o=>o.contactId===c.id),company=opps[0]?getCompany(state,opps[0]):null,active=opps.filter(o=>!['Ganho','Perdido','Adiado'].includes(o.stage)),mrr=opps.filter(o=>o.stage==='Ganho').reduce((s,o)=>s+opportunityTotals(o).mrr,0);return <tr key={c.id}><td><b>{c.name}</b><small>{c.phone||c.email||'Sem contato'}</small></td><td>{company?.name||'—'}<small>{company?.type||''}</small></td><td>{opps.length}</td><td>{active.length}</td><td>{money(mrr)}</td><td><button className="btn small" onClick={()=>newForContact(c)}>Nova oportunidade</button>{opps[0]&&<button className="link-btn" onClick={()=>openOpportunity(opps[0].id)}>Abrir</button>}</td></tr>})}</tbody></table></section>:<section className="panel table-wrap"><table><thead><tr><th>Lead</th><th>Serviços</th><th>Etapa</th><th>Score</th><th>Potencial</th><th></th></tr></thead><tbody>{state.opportunities.filter(o=>{const c=state.contacts.find(x=>x.id===o.contactId);return!q||`${c?.name} ${serviceNames(o)}`.toLowerCase().includes(q.toLowerCase())}).map(o=><tr key={o.id}><td><b>{state.contacts.find(c=>c.id===o.contactId)?.name}</b><small>{getCompany(state,o)?.name}</small></td><td>{serviceNames(o)}</td><td><span className="pill neutral">{o.stage}</span></td><td><span className="score">{scoreLead(state,o)}/100</span></td><td>{money(opportunityTotals(o).oneOff)}<small>{opportunityTotals(o).mrr?`${money(opportunityTotals(o).mrr)}/mês`:''}</small></td><td><button className="link-btn" onClick={()=>openOpportunity(o.id)}>Abrir</button></td></tr>)}</tbody></table></section>}</>
}
