import React, { useState } from 'react'
import { useCrm } from '../context/CrmContext.jsx'
import { PIPELINE_STAGES } from '../data/catalog.js'
import { getContact, opportunityTotals, scoreLead, serviceNames, stageAge } from '../lib/domain.js'
import { money } from '../lib/utils.js'
export default function Pipeline({openOpportunity}){
 const {state,setStage,markWon,notify}=useCrm();const [q,setQ]=useState('');const [temp,setTemp]=useState('')
 const matches=o=>{const c=getContact(state,o);return(!temp||o.temp===temp)&&(!q||`${c?.name} ${serviceNames(o)}`.toLowerCase().includes(q.toLowerCase()))}
 return <><div className="toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar lead, empresa ou serviço"/><select value={temp} onChange={e=>setTemp(e.target.value)}><option value="">Todas as temperaturas</option><option value="hot">Quentes</option><option value="warm">Mornos</option><option value="cold">Frios</option></select></div><div className="kanban">{PIPELINE_STAGES.map(stage=>{const list=state.opportunities.filter(o=>o.stage===stage&&matches(o)),sum=list.reduce((a,o)=>{const t=opportunityTotals(o);a.one+=t.oneOff;a.mrr+=t.mrr;return a},{one:0,mrr:0});return <section className="kanban-column" key={stage} onDragOver={e=>e.preventDefault()} onDrop={e=>{const id=e.dataTransfer.getData('text/plain');if(!id)return;if(stage==='Ganho'){markWon(id);notify('Venda marcada como ganha.')}else setStage(id,stage)}}><header><div className="between"><b>{stage}</b><span className="count">{list.length}</span></div><small>{money(sum.one)}{sum.mrr?` · ${money(sum.mrr)}/mês`:''}</small></header>{list.map(o=><article className="op-card" draggable key={o.id} onDragStart={e=>e.dataTransfer.setData('text/plain',o.id)} onClick={()=>openOpportunity(o.id)}><div className="between"><b>{getContact(state,o)?.name}</b><span className={`pill ${o.temp}`}>{o.temp==='hot'?'Quente':o.temp==='warm'?'Morno':'Frio'}</span></div><p>{serviceNames(o)}</p><div className="tags"><span className="score">Score {scoreLead(state,o)}/100</span><span className="pill neutral">{stageAge(o)}d na etapa</span></div><strong className="op-value">{money(opportunityTotals(o).oneOff)}{opportunityTotals(o).mrr?<small> + {money(opportunityTotals(o).mrr)}/mês</small>:null}</strong></article>)}</section>})}</div></>
}
