import React, { useState } from 'react'
import MetricCard from '../components/MetricCard.jsx'
import FilterChips from '../components/FilterChips.jsx'
import { useCrm } from '../context/CrmContext.jsx'
import { reportData } from '../lib/domain.js'
import { money } from '../lib/utils.js'
export default function Reports(){
 const {state}=useCrm();const[period,setPeriod]=useState('month');const r=reportData(state,period);const max=Math.max(1,...Object.values(r.bySource).map(x=>x.leads))
 const services={};r.created.forEach(o=>(o.items||[]).forEach(i=>{services[i.name]??={leads:0,wins:0};services[i.name].leads++}));r.won.forEach(o=>(o.items||[]).forEach(i=>{services[i.name]??={leads:0,wins:0};services[i.name].wins++}))
 return <><div className="filter-stack"><FilterChips label="Período" value={period} onChange={setPeriod} items={[["month","Este mês"],["30","30 dias"],["all","Todo período"]]}/></div><div className="metrics-grid"><MetricCard label="Conversão" value={`${r.conversion.toFixed(1)}%`} hint={`${r.won.length} ganhos em ${r.won.length+r.lost.length} decisões`}/><MetricCard label="Receita avulsa" value={money(r.revenue.oneOff)} hint="Pela data real do fechamento"/><MetricCard label="Novo MRR" value={money(r.revenue.mrr)} hint="Pela data real do fechamento"/><MetricCard label="Ticket médio MRR" value={money(r.won.length?r.revenue.mrr/r.won.length:0)}/></div><div className="two-grid"><section className="panel"><header className="panel-head"><h2>Origem dos leads</h2></header><div className="panel-body">{Object.entries(r.bySource).sort((a,b)=>b[1].leads-a[1].leads).map(([name,x])=><div className="bar-row" key={name}><span>{name}</span><div className="bar-track"><span style={{width:`${x.leads/max*100}%`}}/></div><b>{x.wins}/{x.leads}</b><small>{money(x.mrr)} MRR</small></div>)}{!Object.keys(r.bySource).length&&<div className="empty">Sem dados.</div>}</div></section><section className="panel"><header className="panel-head"><h2>Motivos de perda</h2></header><div className="panel-body list-stack">{Object.entries(r.lossReasons).map(([name,count])=><div className="list-row" key={name}><span className="status-dot danger"/><span><b>{name}</b><small>{count} negociação(ões)</small></span></div>)}{!Object.keys(r.lossReasons).length&&<div className="empty">Sem perdas no período.</div>}</div></section></div><section className="panel table-wrap spaced"><header className="panel-head"><h2>Conversão por serviço</h2></header><table><thead><tr><th>Serviço</th><th>Entradas no período</th><th>Ganhos no período</th><th>Conversão indicativa</th></tr></thead><tbody>{Object.entries(services).map(([name,x])=><tr key={name}><td>{name}</td><td>{x.leads}</td><td>{x.wins}</td><td>{x.leads?`${(x.wins/x.leads*100).toFixed(1)}%`:'—'}</td></tr>)}</tbody></table></section></>
}
